#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py collectstatic --no-input
python manage.py loaddata dev.yaml
uvicorn config.asgi:application \
    --host 0.0.0.0 \
    --reload \
    --reload-dir src
