# Generated by Django 4.1.11 on 2024-09-10 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('threshold', models.CharField(max_length=255)),
                ('scheme_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_criteria', to='schemes.scheme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('scheme_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_benefit', to='schemes.scheme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
