# Generated by Django 4.1.11 on 2024-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemecriteria',
            name='field',
            field=models.CharField(choices=[('employment_status', 'Employment Status'), ('sex', 'Sex'), ('age', 'Age'), ('marital_status', 'Marital Status')], max_length=255),
        ),
    ]
