# Generated by Django 4.1.11 on 2024-09-10 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], max_length=20)),
                ('employment_status', models.CharField(choices=[('unemployed', 'Unemployed'), ('employed', 'Employed')], max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('male', 'M'), ('female', 'F')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicantHousehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], default='single', max_length=20)),
                ('employment_status', models.CharField(choices=[('unemployed', 'Unemployed'), ('employed', 'Employed')], default='unemployed', max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('male', 'M'), ('female', 'F')], max_length=10, null=True)),
                ('relation', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('son', 'Son'), ('daughter', 'Daugther')], max_length=50)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='applicants.applicant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
